import { defineConfig, globalIgnores } from 'eslint/config';
import nextVitals from 'eslint-config-next/core-web-vitals';
import nextTs from 'eslint-config-next/typescript';

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    '.next/**',
    'out/**',
    'build/**',
    'next-env.d.ts',
    // Generated by `npm run test:coverage`; not ours to lint.
    'coverage/**',
  ]),
  {
    // The codebase already uses a leading underscore to mean "required by the
    // signature, deliberately unused" — every useActionState action takes a
    // `_prevState` it ignores. The default `args: after-used` only tolerates
    // that when a used parameter follows, so a read-only action that ignores
    // BOTH trailing parameters would warn despite following the convention.
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'warn',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
    },
  },
]);

export default eslintConfig;
